name: Autograding Tests
'on':
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Test for output from car.py
      id: test-for-output-from-car-py
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Test for output from car.py
        setup-command: ''
        command: "./python car.py"
        input: ''
        expected-output: "[\\S\\s]+[\\S]+"
        comparison-method: regex
        timeout: 1
        max-score: 1
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST-FOR-OUTPUT-FROM-CAR-PY_RESULTS: "${{steps.test-for-output-from-car-py.outputs.result}}"
      with:
        runners: test-for-output-from-car-py
